# fly.toml app configuration file generated for leptos-cv-resume on 2024-01-21T18:25:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leptos-cv-resume"
primary_region = "ams"

[build]

[http_service]
  http_checks = []
  internal_port = 8043
  force_https = true
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
